import type { Metadata } from "next";
import "./globals.css";

import localFont from "next/font/local";
import Navbar from "./components/layout/header/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const GeistVF = localFont({
  src: "../public/fonts/GeistVF.woff",
})
export default function RootLayout({

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`bg-gray-200 dark:bg-black text-gray-100 ${GeistVF.className}`}
      >
        <header className="relative z-50">
          <Navbar />
        </header>
        <main>
          {/* <Suspense fallback={<Loading/>}> */}
            {children}
          {/* </Suspense> */}
        </main>

      </body>
    </html>
  );
}
